version: 1
update_configs:
  - package_manager: "java:maven"
    directory: "/"
    update_schedule: "daily"
    automerged_updates:
      - match: { dependency_type: "development", update_type: "semver:minor" }
      - match: { dependency_type: "production", update_type: "semver:minor" }
    ignored_updates:
      - match:
          dependency_name: "zeebe*" # Zeebe dependencies will be manually updated
